project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Madhavi Sen"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/madhavi2104
      - icon: linkedin
        href: https://linkedin.com/in/madhavi-sen-118887205
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

